Session 4
iuresti/workshop-springboot pull request #10
Opened 2019-05-14 22:47 UTC by rid3r77

Cambios correspondientes a la session-4 del workshop de spring boot.

Principales modificaciones:
- Inclusion de nuevas dependencias.
- Inclusion de seguridad (Spring Security/JWT) en todas las rutas de la aplicacion.
- Modificacion en Repository/Service/ServiceImpl/Controllers User/Board/Column/Card.
- Inclusion de Roles de usuario.
- Inclusion de forms para crear/editar Board/Column/Card.
- Modificacion de ErrorHandler para el manejo de nuevas excepiones. 
- Eliminacion de Rabbit MQ. Inclusion de H2.
- Modificacion de migraciones de Flyway. 

Dichas modificaciones han sido verificadas, prueba de ello se encuentra en la rama Session-5 del fork de este mismo repositorio en mi cuenta.

2019-05-15 14:20 UTC, iuresti requested changes
Thanks so much for the changes... They look so good, the general comment is to remove commented code everywhere only.

2019-05-15 14:20 UTC, iuresti commented on pom.xml
> +<!--        <dependency>-->
If this is not needed anymore would be better to remove it

2019-05-15 14:20 UTC, iuresti commented on src/main/java/org/desarrolladorslp/workshops/springboot/config/RabbitMQConfiguration.java
>  public class RabbitMQConfiguration {
Let's remove this clases as well if we are not using rabbit anymore

2019-05-15 14:20 UTC, iuresti commented on src/main/java/org/desarrolladorslp/workshops/springboot/controllers/BoardController.java
> +//    private RabbitTemplate rabbitTemplate;
Will be clearer if we remove this unnused code

2019-05-15 14:20 UTC, iuresti commented on src/main/java/org/desarrolladorslp/workshops/springboot/forms/ColumnForm.java
> +@Data
Nice... I think you'll need to include some slides to talk about Lombok (in case you hadn't considered it yet) and some time to install IDE plugins

2019-05-17 18:02 UTC, rid3r77 commented
All the irrelevant line codes, comments, and  dependencies have been removed. Code is not clean.

2019-05-23 03:29 UTC, iuresti approved these changes

2019-05-23 03:34 UTC, merged